### ISSUE TITLE
Database error when creating users

### ISSUE THREAD

**Issue by Techtony96** [erev0s/VAmPI#59]
Similar possibly to #58 

Clean setup/install using docker. Error that table users doesn't exist when creating a new user.

```yml
version: "3"
services:
 vampi-secure:
  image: erev0s/vampi:latest
  container_name: vampi-secure
  ports:
   - 5001:5000
  environment:
   - vulnerable=0
  networks:
   - nginx_nginx-net

 vampi-vulnerable:
  image: erev0s/vampi:latest
  container_name: vampi-vulnerable
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
  networks:
   - nginx_nginx-net

networks:
    nginx_nginx-net:
        external: true
```

```
vampi# docker logs vampi-vulnerable 
 * Serving Flask app 'config'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.6:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 108-280-572
172.19.0.3 - - [22/Jul/2024 19:05:51] "GET / HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:05:51] "GET /favicon.ico HTTP/1.1" 404 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui HTTP/1.1" 308 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui/ HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui/swagger-ui.css HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui/swagger-ui-bundle.js HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /openapi.json HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:17] "GET /ui/favicon-32x32.png HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:21:28] "GET /ui/openapi.json HTTP/1.1" 404 -
172.19.0.3 - - [22/Jul/2024 19:21:28] "GET /favicon.ico HTTP/1.1" 404 -
172.19.0.3 - - [22/Jul/2024 19:21:35] "GET /openapi.json HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:22:20] "GET /openapi.json HTTP/1.1" 200 -
172.19.0.3 - - [22/Jul/2024 19:23:24] "POST /users/v1/register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: users

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/vampi/api_views/users.py", line 39, in register_user
    user = User.query.filter_by(username=request_data.get('username')).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2769, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2872, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 252, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users.email AS users_email, users.admin AS users_admin 
FROM users 
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('user1', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by erev0s** [comment]
@Techtony96 thank you for the logs ! now i can see what is wrong.
You have to first issue a request to create/populate the database and then you can register the user. To do that, first issue the relevant request `GET /createdb`, You should get a response

~~~~
{
    "message": "Database populated."
}
~~~~

Then you can register your user.
Please let me know if that works.

> [!TIP]
> You can import in Postman the available collection and run it, you must get 200/204 in all requests except the last one that is available only for admins and returns 401.

**Comment by Techtony96** [comment]
Ah, that was the issue. I completely forgot that had to be done. Might be nice to have that mentioned in the install steps, or even run automatically if the DB is empty.

Thanks for the quick response!
